### ISSUE TITLE
Have a global server directory

### ISSUE THREAD

**Issue by Eufranio** [ImMorpheus/SpongeStart#21]
At the moment, every project has it's own whole server on it's `run` directory. What if there were global directories for each server version? So we could have like `IdeaProjects/run/1.12.2/vanilla/` and it would reuse this server for all 1.12.2 SpongeStart projects. It'd be nice and wouldn't waste a lot of disk space.

**Comment by ImMorpheus** [comment]
You can already do this.
From the README

>     forgeServerFolder ''    //absolute path to the forge server folder. Default to run/forge
>     vanillaServerFolder ''  //absolute path to the vanilla server folder. Default to run/vanilla

**Comment by Eufranio** [comment]
Exactly what I needed.
