### ISSUE TITLE
Can't find Forge version

### ISSUE THREAD

**Issue by randombyte-developer** [ImMorpheus/SpongeStart#22]
When specifying `1.12.2-2768-7.1.6-RC3616` as the SpongeForge version, it will end here: https://github.com/ImMorpheus/SpongeStart/blob/fa9437f63e1291dd2d31b657f57e854bc9ac7e87/src/main/java/com/qixalite/spongestart/tasks/download/ForgeDownloadTask.java#L49

**Comment by ImMorpheus** [comment]
@randombyte-developer Post you build.gradle

I'm not able to reproduce this with:

```
spongestart {
    minecraft '1.12.2'
    spongeForge '1.12.2-2768-7.1.6-RC3616'
}
```

Did you specify the minecraft version ?

**Comment by randombyte-developer** [comment]
What the heck, now it works for me again...
